name: errors
description: Dart package which manages app common errors.
version: 2.0.0
publish_to: none

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  #equatable: ^2.0.5
  #meta: ^1.8.0
  freezed_annotation: ^2.2.0
  equatable: ^2.0.0
  meta: ^1.3.0

dev_dependencies:
  lints: ^2.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  freezed: ^2.3.2